name: GhastGolemFix
version: 1.1
main: com.blockbuster.ghastgolem.GhastGolemFix
api-version: 1.20

commands:
  ghastgolem:
    description: Manage GhastGolemFix
    usage: /ghastgolem <status|reload|on|off>
    permission: ghastgolem.admin

permissions:
  ghastgolem.admin:
    description: Allows managing GhastGolemFix
    default: op
